# Generated by Django 2.2.4 on 2020-03-05 03:26

from django.db import migrations, models
import drf_social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('provider', models.CharField(choices=[(provider, provider) for provider in drf_social.models.Providers], max_length=10)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('scopes', models.TextField(default='[]')),
            ],
        ),
    ]
